if 1:
	if 1:
		raise NameError('YourNameIncorrect')
	elif 1:
		raise NameError('YourNameIncorrect')
elif 1:
	if 1:
		raise NameError('YourNameIncorrect')
	elif 1:
		raise NameError('YourNameIncorrect')
