with 1:
	with 1:
		raise NameError('YourNameIncorrect')
		raise NameError('YourNameIncorrect')
		print 1
	with 1:
		raise NameError('YourNameIncorrect')
		raise NameError('YourNameIncorrect')
		print 1
	print 1
